---
title: "Letter to Editor"
author: ""
editor: visual
---

!! A mettre à jour lorsque le fichier latex sera terminé.

## Associate Editor

-   Three external reviewers have thoroughly examined your work. While their reports are positive overall, they point out a number of possible improvements and raise several questions (in particular regarding the novelty, the numerical experiments, the figures, and the reproducibility of the work) that do not allow your contribution to be published in its current form.

> **authors' answer:** Improvements taking in account the reviewers questions haven been undertaken. Details are given in the following.

-   Let me add some specific comments regarding reproducibility: the reviewers did not manage to reproduce your results (and neither did I). One of them provides a detailed description of their attempts, which should be very useful for you to address this issue. In particular, the install_conesta() function does not seem to work on all systems. It is fine to provide a R package that calls python code via reticulate, but this can be fragile and difficult to maintain. A possibly more robust alternative to avoid these difficulties would be to have all the fitting part in python.

> **authors' answer:** R package

> **authors' answer:** Python package
